name = "PhDSE"
uuid = "7ecd2ffa-f4c5-4dad-8846-8d8820c20168"
authors = ["Jonathan Schmidt <jonathan.schmidt@uni-tuebingen.de> and contributors"]
version = "0.1.0"

[deps]
GaussianDistributions = "43dcc890-d446-5863-8d1a-14597580bb8d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PSDMatrices = "fe68d972-6fd8-4755-bdf0-97d4c54cefdc"

[compat]
PSDMatrices = "0.4"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
